# -*- coding: utf-8 -*-
"""DS 11-3-26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G4p_lEJz6pXG88FbkH1q-gmTvULzPbZe
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/House Price.csv')
df.head()

missing_values = df.isnull().sum()
print(missing_values)

missing = df.isnull().sum()
missing = missing[missing > 0]
print(missing)

total_missing = df.isnull().sum().sum()
print("Total Missing Values:", total_missing)

missing_percentage = (df.isnull().sum() / len(df)) * 100
print(missing_percentage)

missing_summary = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": (df.isnull().sum() / len(df)) * 100
})

print(missing_summary[missing_summary["Missing Values"] > 0])